# Variables
$scriptsDir = $HOME/.config/hypr/scripts

# Sync Wayland environment with systemd and DBus
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = nwg-look -a # Apply stored gsettings
# exec-once = /usr/lib/hyprpolkitagent/hyprpolkitagent # Polkit agent
exec-once = $scriptsDir/portal-hyprland.sh # Portal Hyprland
# exec-once = $scriptsDir/cursor-warps.sh # Warp cursor to the center of newly opened windows
exec-once = qs -c noctalia-shell --no-duplicate # Noctalia shell
 # Always laptop screen awake on startup (fix for lid switch)
exec-once = echo "monitor = eDP-1, 1920x1080, 1920x0, 1" > $HOME/.config/hypr/configs/laptop-display.conf
